package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	v1 "github.com/go-training/gin-connect-demo/gen/proto/v1"        // generated by protoc-gen-go
	"github.com/go-training/gin-connect-demo/gen/proto/v1/v1connect" // generated by protoc-gen-connect-go

	"github.com/bufbuild/connect-go"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

type GiteaServer struct{}

func (s *GiteaServer) Gitea(
	ctx context.Context,
	req *connect.Request[v1.GiteaRequest],
) (*connect.Response[v1.GiteaResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&v1.GiteaResponse{
		Giteaing: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Gitea-Version", "v1")
	return res, nil
}

func main() {
	greeter := &GiteaServer{}
	mux := http.NewServeMux()
	path, handler := v1connect.NewGiteaServiceHandler(greeter)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
