package main

import (
	"context"
	"log"
	"net/http"

	v1 "github.com/go-training/gin-connect-demo/gen/proto/v1"        // generated by protoc-gen-go
	"github.com/go-training/gin-connect-demo/gen/proto/v1/v1connect" // generated by protoc-gen-connect-go

	"github.com/bufbuild/connect-go"
)

func main() {
	client := v1connect.NewGiteaServiceClient(
		http.DefaultClient,
		"http://localhost:8080/",
	)
	req := connect.NewRequest(&v1.GiteaRequest{
		Name: "foobar",
	})
	req.Header().Set("Some-Header", "hello from connect")
	res, err := client.Gitea(context.Background(), req)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(res.Msg)
}
