package main

import (
	"context"
	"crypto/tls"
	"log"
	"net"
	"net/http"
	"time"

	v1 "github.com/go-training/proto-connect-demo/gen/proto/v1"        // generated by protoc-gen-go
	"github.com/go-training/proto-connect-demo/gen/proto/v1/v1connect" // generated by protoc-gen-connect-go

	"github.com/bufbuild/connect-go"
	"golang.org/x/net/http2"
)

func main() {
	c := &http.Client{
		Timeout: 5 * time.Second,
		Transport: &http2.Transport{
			AllowHTTP: true,
			DialTLS: func(netw, addr string, cfg *tls.Config) (net.Conn, error) {
				return net.Dial(netw, addr)
			},
		},
	}

	connectGiteaClient := v1connect.NewGiteaServiceClient(
		c,
		"http://localhost:8080/",
	)

	grpcGiteaClient := v1connect.NewGiteaServiceClient(
		c,
		"http://localhost:8080/",
		connect.WithGRPC(),
	)

	giteaClients := []v1connect.GiteaServiceClient{connectGiteaClient, grpcGiteaClient}

	for _, client := range giteaClients {
		req := connect.NewRequest(&v1.GiteaRequest{
			Name: "foobar",
		})
		req.Header().Set("Gitea-Header", "hello from connect")
		res, err := client.Gitea(context.Background(), req)
		if err != nil {
			log.Fatalln(err)
		}
		log.Println("Message:", res.Msg.Giteaing)
		log.Println("Gitea-Version:", res.Header().Get("Gitea-Version"))
	}

	connectPingClient := v1connect.NewPingServiceClient(
		c,
		"http://localhost:8080/",
	)

	grpcPingClient := v1connect.NewPingServiceClient(
		c,
		"http://localhost:8080/",
		connect.WithGRPC(),
	)

	pingClients := []v1connect.PingServiceClient{connectPingClient, grpcPingClient}

	for _, client := range pingClients {
		req := connect.NewRequest(&v1.PingRequest{
			Data: "Ping",
		})
		req.Header().Set("Gitea-Header", "hello from connect")
		res, err := client.Ping(context.Background(), req)
		if err != nil {
			log.Fatalln(err)
		}
		log.Println("Message:", res.Msg.Data)
		log.Println("Gitea-Version:", res.Header().Get("Gitea-Version"))
	}
}
