package main

import (
	"context"
	"crypto/tls"
	"log"
	"net"
	"net/http"

	v1 "github.com/go-training/gin-connect-demo/gen/proto/v1"        // generated by protoc-gen-go
	"github.com/go-training/gin-connect-demo/gen/proto/v1/v1connect" // generated by protoc-gen-connect-go

	"github.com/bufbuild/connect-go"
	"golang.org/x/net/http2"
)

func main() {
	c := &http.Client{
		Transport: &http2.Transport{
			AllowHTTP: true,
			DialTLS: func(netw, addr string, cfg *tls.Config) (net.Conn, error) {
				return net.Dial(netw, addr)
			},
		},
	}

	client := v1connect.NewGiteaServiceClient(
		c,
		"http://localhost:8080/",
	)
	req := connect.NewRequest(&v1.GiteaRequest{
		Name: "foobar",
	})
	req.Header().Set("Gitea-Header", "hello from connect")
	res, err := client.Gitea(context.Background(), req)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Message:", res.Msg.Giteaing)
	log.Println("Gitea-Version:", res.Header().Get("Gitea-Version"))
}
